apiVersion: apps/v1
kind: Deployment
metadata:
  name: t-rex-app
  namespace: t-rex-app
  labels:
    app: t-rex-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t-rex-app
  template:
    metadata:
      labels:
        app: t-rex-app
    spec:
      containers:
      - name: t-rex-app
        image: gcr.io/acm-demos/t-rex-app:1.0.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "100m"
            memory: "1Gi"
        securityContext:
          runAsUser: 2000
          allowPrivilegeEscalation: false
          privileged: false
